server:
  port: 8888

#spring:
#  thymeleaf:
#    prefix: classpath:/templates/
#    fuffix: .html
#    mode: HTML
#    encoding: UTF-8
#    cache: false

spring:
  application:
    name: word-reader
